// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace BookApi.Models
{
    public partial class Book
    {
        internal static Book DeserializeBook(JsonElement element)
        {
            int id = default;
            string title = default;
            string author = default;
            Optional<string> summary = default;
            Type type = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("id"))
                {
                    id = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("title"))
                {
                    title = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("author"))
                {
                    author = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("summary"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        summary = null;
                        continue;
                    }
                    summary = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("type"))
                {
                    type = new Type(property.Value.GetString());
                    continue;
                }
            }
            return new Book(id, title, author, summary.Value, type);
        }
    }
}
