// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace BookApi.Models
{
    /// <summary> The Book. </summary>
    public partial class Book
    {
        /// <summary> Initializes a new instance of Book. </summary>
        /// <param name="id"></param>
        /// <param name="title"></param>
        /// <param name="author"></param>
        /// <param name="type"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="title"/> or <paramref name="author"/> is null. </exception>
        internal Book(int id, string title, string author, Type type)
        {
            if (title == null)
            {
                throw new ArgumentNullException(nameof(title));
            }
            if (author == null)
            {
                throw new ArgumentNullException(nameof(author));
            }

            Id = id;
            Title = title;
            Author = author;
            Type = type;
        }

        /// <summary> Initializes a new instance of Book. </summary>
        /// <param name="id"></param>
        /// <param name="title"></param>
        /// <param name="author"></param>
        /// <param name="summary"></param>
        /// <param name="type"></param>
        internal Book(int id, string title, string author, string summary, Type type)
        {
            Id = id;
            Title = title;
            Author = author;
            Summary = summary;
            Type = type;
        }

        /// <summary> Gets the id. </summary>
        public int Id { get; }
        /// <summary> Gets the title. </summary>
        public string Title { get; }
        /// <summary> Gets the author. </summary>
        public string Author { get; }
        /// <summary> Gets the summary. </summary>
        public string Summary { get; }
        /// <summary> Gets the type. </summary>
        public Type Type { get; }
    }
}
